### ISSUE TITLE
Can't add more than 20 templates

### ISSUE THREAD

**Issue by kaminlicht** [hlohaus/SheAdvancedTinyMce#12]
## Actual behaviour

    When I try to add more than 20 templates, the 21st will stay for a second - the notification bar appears and says that the template is saved.the last template will disappear aftewards.

## Expected behaviour

    no issues with adding templates via the plugin.

## Environment

Shopware: 5.4.3
PHP: 7.0.27
Plugin version: 1.1.1

## Steps to reproduce

1. install SheAdvancedTinyMce
2. add 20 templates
3. try to add another template

## Checklist

- [X] I have checked [all issues](https://github.com/hlohaus/SheAdvancedTinyMce/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [X] I am using the latest stable version of this plugin.

**Comment by hlohaus** [comment]
Yes, the paging are missing. I added them.

**Comment by kaminlicht** [comment]
Thanks for your fast reply/fix.

I've installed the update. unfortunately, it's still not working.
So the issue still occurs.

**Comment by kaminlicht** [comment]
@hlohaus 
This isssue isn't solved, yet. So it shouldn't be closed.
Thank you.
