### ISSUE TITLE
Shopware plugin Erweiterter TinyMCE

### ISSUE THREAD

**Issue by tee-le-shop** [hlohaus/SheAdvancedTinyMce#15]
## Actual behaviour

Ich habe ein neues Freitextfeld in Tabelle s_user_attributes als
Spaltentyp HTML-Editor - MEDIUMTEXT
im Backend anzeigen = 'X'
Schreibgeschütz im Backend = 'X'
angelegt.
Dieses Feld wird dann in einem Plugin mit einer HTML Tabelle befüllt und in der DB gespeichert.
Die Anzeige im Kundenstamm ist korrekt und das Feld, ist wie gewünscht, nur anzeigbar.
Gehe ich nach der Anzeige im Kundenstamm z.B. in den Artikelstamm ist auch hier der Editor für die Beschreibung ausgeschaltet und das Feld ist nun auch nicht änderbar.

Starte ich dann den Admin erneut, ist der Editor wieder sichtbar.

Das Phänomen tritt auch mit dem erweiterten Shopware Editor auf.

Kann man diesem Problem durch Einstellungen in Ihrem Plugin beheben?

Vielen Dank im Voraus.
 
## Expected behaviour
information
## Environment
Shopware Version: 5.6.4, Plugin Version: 1.1.3, PHP 7.2

## Steps to reproduce

1. Freitextfeld für z.B. Tabelle s_user_attributes als HTML Editor Feld anlegen
2. "Im Backend anzeigen" auswählen
3. "Schreibgeschützt im Backend" auswählen
4. Feld im Kundenstamm anzeigen
5. Artikelverwaltung aufrufen. Hier ist der Editor nun auch ausgeschaltet.

## Checklist

- [ ] I have checked [all issues](https://github.com/hlohaus/SheAdvancedTinyMce/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ ] I am using the latest stable version of this plugin.

--

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by hlohaus** [comment]
Wieso dann?
Schreibgeschütz im Backend = 'X'
Das soll ja die Funktion sein.
