### ISSUE TITLE
Darstellungsproblem (Chrome, FF) Button zum Einfügen von Vorlagen / Auswahlliste Anzeige unvollständig

### ISSUE THREAD

**Issue by klausmad** [hlohaus/SheAdvancedTinyMce#2]
## Actual behaviour

 Button zum Einfügen von Vorlagen wird abgeschnitten.

![grafik](https://user-images.githubusercontent.com/22545981/52161593-96b06200-26c7-11e9-922d-22b23074d0f1.png)

## Expected behaviour

    Button sollte für optimale Usability komplett sichtbar sein. CSS Anpassung ?

## Environment

 SW 5.5.6 auf PHP 7.2. FPM, Browser Chrome und FF getetstet

## Steps to reproduce

1. Vorlage anlegen
2. Artikel öffnen
3. Verwende Button "Inhalt aus Vorlage einfügen"
4. Fenster öffnet...Button unten abgeschnitten

## Checklist

- [ x] I have checked [all issues](https://github.com/hlohaus/SheAdvancedTinyMce/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x ] I am using the latest stable version of this plugin.

--

**Comment by klausmad** [comment]
EDIT:

2 Vorlagen angelegt, Cache gelöscht, aber Vorlagen erscheinen nicht in der Auswahlliste (Chrome, FF getestet)

![grafik](https://user-images.githubusercontent.com/22545981/52163576-22d08280-26e4-11e9-8a59-01ca36a230b0.png)

![grafik](https://user-images.githubusercontent.com/22545981/52163587-4e536d00-26e4-11e9-8492-7f9fe38dd6a2.png)

**Comment by klausmad** [comment]
Hi,

- super, deutlich besser...Buttons nur noch wenig eingeschränkt, gut 75 % sichtbar...
- 
- Liste der Vorlagen nun vollständig sichtbar...

perfekt, danke Dir... dise Funktions sollte eigentlich Standard sein in SW...erleichtert die Neuanlage optisch bei allen Artikeln gleich zu haben enorm.....gute Arbeit.

![grafik](https://user-images.githubusercontent.com/22545981/52165371-54efdd80-2700-11e9-8bec-e01924eea63b.png)

**Comment by klausmad** [comment]
Button Position noch besser mit

```
$(document).ready(function() {
    $("body").css('margin-top', -10);
})

```
![grafik](https://user-images.githubusercontent.com/22545981/52165712-81a5f400-2704-11e9-815b-cd42dfa084bf.png)


![grafik](https://user-images.githubusercontent.com/22545981/52165704-6a670680-2704-11e9-9fc9-d0a6159a9bcb.png)

**Comment by hlohaus** [comment]
with Version 1.0.1

**Comment by Forestsoft-de** [comment]
Hey 

> EDIT:
> 
> 2 Vorlagen angelegt, Cache gelöscht, aber Vorlagen erscheinen nicht in der Auswahlliste (Chrome, FF getestet)
> 
> ![grafik](https://user-images.githubusercontent.com/22545981/52163576-22d08280-26e4-11e9-8a59-01ca36a230b0.png)
> 
> ![grafik](https://user-images.githubusercontent.com/22545981/52163587-4e536d00-26e4-11e9-8492-7f9fe38dd6a2.png)

Das gleiche Problem haben wir auch und in der console erscheint folgendes:

![image](https://user-images.githubusercontent.com/132578/53083088-8a693900-34fe-11e9-9c61-fb938f0933a7.png)
