### ISSUE TITLE
 Update from 1.0.2 to 1.0.3 failed

### ISSUE THREAD

**Issue by klausmad** [hlohaus/SheAdvancedTinyMce#5]
## Actual behaviour

 Update from (1.0.1) 1.0.2 to 1.0.3 failed

## Expected behaviour

    Version 1.0.3 should be final release (or maybe 1.0.2 ??)

## Environment

SW 5.5.6 prof. php 7.2. fpm 

## Steps to reproduce

try update, think version in plugin.xml should be 1.0.3 

![grafik](https://user-images.githubusercontent.com/22545981/53754738-23ac2e00-3eb5-11e9-8a7a-4345a8593697.png)

![grafik](https://user-images.githubusercontent.com/22545981/53754930-9f0ddf80-3eb5-11e9-9a41-88400eee8e42.png)

## Checklist

- [x ] I have checked [all issues](https://github.com/hlohaus/SheAdvancedTinyMce/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [x ] I am using the latest stable version of this plugin.

**Comment by hlohaus** [comment]
mhh. yes. I updated it to 1.1.0 without changes.
