### ISSUE TITLE
   Update failed again, Pluginmanager show wrong version

### ISSUE THREAD

**Issue by klausmad** [hlohaus/SheAdvancedTinyMce#8]
## Actual behaviour

   Update failed, Pluginmanager show wrong version, but files are changed

## Expected behaviour

  Shown version should be 1.1.0

## Environment

SW 5.5.7 prof

## Steps to reproduce

try to install update, plugin manager show 1.0.3

## Checklist

- [X ] I have checked [all issues](https://github.com/hlohaus/SheAdvancedTinyMce/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [X ] I am using the latest stable version of this plugin.

--

![grafik](https://user-images.githubusercontent.com/22545981/54081683-c971f980-4308-11e9-9625-a22d517ee7b3.png)

show wrong version 1.0.3 and show update 1.1.0 again for install

![grafik](https://user-images.githubusercontent.com/22545981/54081693-f45c4d80-4308-11e9-89c4-a6a180180154.png)

files are changed

![grafik](https://user-images.githubusercontent.com/22545981/54081703-0fc75880-4309-11e9-8e80-c1aac491aec8.png)

**Comment by klausmad** [comment]
sorry, sholud look like this...

![grafik](https://user-images.githubusercontent.com/22545981/54083773-ace5b980-4328-11e9-9787-910bf0e589e6.png)

**Comment by hlohaus** [comment]
okay, should be fixed
